// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    PuztileInfo: typeof import('./src/components/PuztileInfo.vue')['default']
    PuztileRestart: typeof import('./src/components/PuztileRestart.vue')['default']
    PuztileRoot: typeof import('./src/components/PuztileRoot.vue')['default']
    PuztileSize: typeof import('./src/components/PuztileSize.vue')['default']
  }
}

export { }
